FONT_SIZES = {
    "x-small": 0.7,
    "smaller": 0.8,
    "small": 0.9,
    "normal": 1,
    "large": 1.1,
    "larger": 1.2,
    "x-large": 1.3,
}

LOCALE_MAP = {
    "af": "Afrikaans",
    "ar-dz": "Arabic (Algeria)",
    "ar-kw": "Arabic (Kuwait)",
    "ar-ly": "Arabic (Libya)",
    "ar-ma": "Arabic (Morocco)",
    "ar-sa": "Arabic (Saudi Arabia)",
    "ar-tn": "Arabic (Tunisia)",
    "ar": "Arabic",
    "az": "Azerbaijani",
    "bg": "Bulgarian",
    "bn": "Bengali",
    "bs": "Bosnian",
    "ca": "Catalan",
    "cs": "Czech",
    "cy": "Welsh",
    "da": "Danish",
    "de-at": "German (Austria)",
    "de": "German",
    "el": "Greek",
    "en": "English",
    "en-au": "English (Australia)",
    "en-gb": "English (UK)",
    "en-nz": "English (New Zealand)",
    "eo": "Esperanto",
    "es-us": "Spanish (US)",
    "es": "Spanish",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Persian",
    "fi": "Finnish",
    "fr-ca": "French (Canada)",
    "fr-ch": "French (Switzerland)",
    "fr": "French",
    "gl": "Galician",
    "he": "Hebrew",
    "hi": "Hindi",
    "hr": "Croatian",
    "hu": "Hungarian",
    "hy-am": "Armenian",
    "id": "Indonesian",
    "is": "Icelandic",
    "it": "Italian",
    "ja": "Japanese",
    "ka": "Georgian",
    "kk": "Kazakh",
    "km": "Khmer",
    "ko": "Korean",
    "ku": "Kurdish",
    "lb": "Luxembourgish",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "mk": "Macedonian",
    "ms": "Malay",
    "nb": "Norwegian Bokmål",
    "ne": "Nepali",
    "nl": "Dutch",
    "nn": "Norwegian Nynorsk",
    "pl": "Polish",
    "pt-br": "Portuguese (Brazil)",
    "pt": "Portuguese",
    "ro": "Romanian",
    "ru": "Russian",
    "si-lk": "Sinhala (Sri Lanka)",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sm": "Samoan",
    "sq": "Albanian",
    "sr-cyrl": "Serbian (Cyrillic)",
    "sr": "Serbian (Latin)",
    "sv": "Swedish",
    "ta-in": "Tamil (India)",
    "th": "Thai",
    "tr": "Turkish",
    "ug": "Uyghur",
    "uk": "Ukrainian",
    "uz-cy": "Uzbek (Cyrillic)",
    "uz": "Uzbek (Latin)",
    "vi": "Vietnamese",
    "zh-cn": "Chinese (Simplified)",
    "zh-tw": "Chinese (Traditional)",
}

LOCALE_GROUPS = [
    (
        "Common",
        [
            ("en", "English"),
            ("en-gb", "English (UK)"),
            ("en-au", "English (Australia)"),
            ("en-nz", "English (New Zealand)"),
            ("es", "Spanish"),
            ("es-us", "Spanish (US)"),
            ("fr", "French"),
            ("fr-ca", "French (Canada)"),
            ("fr-ch", "French (Switzerland)"),
            ("de", "German"),
            ("de-at", "German (Austria)"),
            ("pt", "Portuguese"),
            ("pt-br", "Portuguese (Brazil)"),
            ("zh-cn", "Chinese (Simplified)"),
            ("zh-tw", "Chinese (Traditional)"),
            ("ja", "Japanese"),
            ("ko", "Korean"),
            ("it", "Italian"),
            ("nl", "Dutch"),
            ("ru", "Russian"),
            ("sv", "Swedish"),
        ],
    ),
    (
        "European",
        [
            ("bg", "Bulgarian"),
            ("bs", "Bosnian"),
            ("ca", "Catalan"),
            ("cs", "Czech"),
            ("cy", "Welsh"),
            ("da", "Danish"),
            ("el", "Greek"),
            ("et", "Estonian"),
            ("eu", "Basque"),
            ("fi", "Finnish"),
            ("gl", "Galician"),
            ("hr", "Croatian"),
            ("hu", "Hungarian"),
            ("is", "Icelandic"),
            ("lb", "Luxembourgish"),
            ("lt", "Lithuanian"),
            ("lv", "Latvian"),
            ("mk", "Macedonian"),
            ("nb", "Norwegian Bokm\u00e5l"),
            ("nn", "Norwegian Nynorsk"),
            ("pl", "Polish"),
            ("ro", "Romanian"),
            ("sk", "Slovak"),
            ("sl", "Slovenian"),
            ("sq", "Albanian"),
            ("sr", "Serbian (Latin)"),
            ("sr-cyrl", "Serbian (Cyrillic)"),
            ("uk", "Ukrainian"),
        ],
    ),
    (
        "Middle Eastern & African",
        [
            ("af", "Afrikaans"),
            ("ar", "Arabic"),
            ("ar-dz", "Arabic (Algeria)"),
            ("ar-kw", "Arabic (Kuwait)"),
            ("ar-ly", "Arabic (Libya)"),
            ("ar-ma", "Arabic (Morocco)"),
            ("ar-sa", "Arabic (Saudi Arabia)"),
            ("ar-tn", "Arabic (Tunisia)"),
            ("fa", "Persian"),
            ("he", "Hebrew"),
            ("ku", "Kurdish"),
            ("tr", "Turkish"),
            ("ug", "Uyghur"),
        ],
    ),
    (
        "South & Southeast Asian",
        [
            ("bn", "Bengali"),
            ("hi", "Hindi"),
            ("id", "Indonesian"),
            ("km", "Khmer"),
            ("ms", "Malay"),
            ("ne", "Nepali"),
            ("si-lk", "Sinhala (Sri Lanka)"),
            ("ta-in", "Tamil (India)"),
            ("th", "Thai"),
            ("vi", "Vietnamese"),
        ],
    ),
    (
        "Central Asian & Caucasus",
        [
            ("az", "Azerbaijani"),
            ("hy-am", "Armenian"),
            ("ka", "Georgian"),
            ("kk", "Kazakh"),
            ("uz", "Uzbek (Latin)"),
            ("uz-cy", "Uzbek (Cyrillic)"),
        ],
    ),
    (
        "Other",
        [
            ("eo", "Esperanto"),
            ("sm", "Samoan"),
        ],
    ),
]
