#!/usr/bin/env python3
"""extract_strings.py — Extract translatable strings from InkyPi source files.

Scans src/templates/ (Jinja2 HTML) and src/ (Python) for calls to the i18n
``_()`` helper and writes a sorted JSON catalogue to translations/extracted.json.

Usage
-----
    # Write/refresh the catalogue:
    python scripts/extract_strings.py

    # Write to a custom path:
    python scripts/extract_strings.py --output path/to/out.json

    # CI check — exit 1 if the catalogue is stale:
    python scripts/extract_strings.py --check

Patterns matched
----------------
Python source:     _("string")  or  _('string')
Jinja2 templates:  {{ _("string") }}  or  {{ _('string') }}

Multi-line strings and f-strings are NOT supported by this simple regex
approach; that is intentional (dynamic strings should not be translated via
this mechanism).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Regex — capture the string literal argument of _("...") or _('...')
# Handles both quote styles; does NOT handle escaped quotes inside the string.
# ---------------------------------------------------------------------------
_PATTERN = re.compile(r"""_\(\s*(?P<q>["'])(?P<msg>(?:(?!(?P=q)).)*?)(?P=q)\s*\)""")


def _scan_file(path: Path) -> list[str]:
    """Return all translatable string literals found in *path*."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    return [m.group("msg") for m in _PATTERN.finditer(text)]


def _collect_strings(src_root: Path) -> list[str]:
    """Walk *src_root* and return a sorted, deduplicated list of strings."""
    found: set[str] = set()
    extensions = {".py", ".html", ".jinja", ".jinja2", ".j2"}

    for root, dirs, files in os.walk(src_root):
        # Skip hidden directories and __pycache__
        dirs[:] = [
            d
            for d in dirs
            if not d.startswith(".") and d != "__pycache__" and d != "node_modules"
        ]
        for fname in files:
            if Path(fname).suffix in extensions:
                path = Path(root) / fname
                found.update(_scan_file(path))

    return sorted(found)


def _build_catalogue(strings: list[str]) -> dict:
    """Return a JSON-serialisable catalogue dict."""
    return {
        "_meta": {
            "description": "Auto-generated by scripts/extract_strings.py — do not edit by hand.",
            "count": len(strings),
        },
        "strings": strings,
    }


def _write_output(catalogue: dict, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(catalogue, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def _is_stale(catalogue: dict, output_path: Path) -> bool:
    """Return True when *output_path* does not match the freshly built catalogue."""
    if not output_path.exists():
        return True
    try:
        existing = json.loads(output_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return True
    # Compare only the strings list, not the _meta block (which includes count).
    return existing.get("strings") != catalogue.get("strings")


def main(argv: list[str] | None = None) -> int:
    repo_root = Path(__file__).resolve().parent.parent
    default_src = repo_root / "src"
    default_output = repo_root / "translations" / "extracted.json"

    parser = argparse.ArgumentParser(
        description="Extract translatable _() strings from InkyPi source files."
    )
    parser.add_argument(
        "--src",
        type=Path,
        default=default_src,
        metavar="DIR",
        help=f"Source root to scan (default: {default_src})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=default_output,
        metavar="PATH",
        help=f"Output JSON path (default: {default_output})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the output file is missing or stale (CI mode).",
    )
    args = parser.parse_args(argv)

    strings = _collect_strings(args.src)
    catalogue = _build_catalogue(strings)

    if args.check:
        if _is_stale(catalogue, args.output):
            print(
                f"STALE: {args.output} does not match the current extraction.",
                file=sys.stderr,
            )
            print(
                "Run `python scripts/extract_strings.py` to update it.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {args.output} is up to date ({len(strings)} strings).")
        return 0

    _write_output(catalogue, args.output)
    print(f"Wrote {len(strings)} strings to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
