name: Docs link check

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 5 * * *'

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --verbose README.md docs/**/*.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


