name: Docs link check

on:
  pull_request:
    paths:
      - 'README.md'
      - 'docs/**'
  schedule:
    - cron: '0 5 * * *'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --verbose README.md docs/**/*.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


