name: Tests (pytest)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11', '3.12' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libopenjp2-7 \
            libopenblas-dev \
            libfreetype6-dev \
            fonts-noto-color-emoji

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r install/requirements.txt -r install/requirements-dev.txt

      - name: Run tests
        env:
          INKYPI_ENV: dev
          INKYPI_NO_REFRESH: '1'
          PYTHONPATH: src
        run: |
          pytest
